### ISSUE TITLE
Common Issue

### ISSUE THREAD

**Issue by wkkskskdkkd** [bibee-emio/MedusaMusic#1]

**Comment by bibee-emio** [comment]
Edit the line 152 like below in `pytube\parser.py`.
```python
func_regex = re.compile(r"function\([^)]+\)")
```
to -->
```python
func_regex = re.compile(r"function\([^)]?\)")
```

https://stackoverflow.com/questions/70060263

[@MedusaMousikibot](https://t.me/MedusaMousikibot) also now works fine.

Enjoy 🎊️
