### ISSUE TITLE
Why is it not working for us when we add the codes through heroku?

### ISSUE THREAD

**Issue by cokepokess** [bibee-emio/MedusaMusic#2]

**Comment by bibee-emio** [comment]
**Can u explain your issue little bit more?**
🙄️

**Comment by bibee-emio** [comment]
**There is no error on deploying the code to heroku.**

* _Just click on the **Deploy to Heroku** button_.
* Then fill up the below values with your own.
<img src=https://user-images.githubusercontent.com/93535892/153348940-e713d605-ae34-4620-bc5e-a88b44925134.png height=600 >

* Now time to **Deploy App**.
<hr>

**Attension**
<ul type=circle>
<li>Although, She will show a error while someone try to download a song. You should up to date with <b>Pytube</b> library.</li>
</ul>
